#!/bin/bash
echo "🔧 Fixing Module Import Errors"
echo "=============================="
echo ""
echo "Step 1: Close Xcode completely"
echo "Step 2: Run this command to clear derived data:"
echo ""
echo "rm -rf ~/Library/Developer/Xcode/DerivedData/"
echo ""
echo "Step 3: Clear module cache:"
echo "rm -rf ~/Library/Caches/org.swift.swiftpm"
echo ""
echo "Step 4: Open Xcode and try these in order:"
echo "  a) File → Packages → Reset Package Caches"
echo "  b) Wait for 'Resolving Package Graph' to complete"
echo "  c) File → Packages → Update to Latest Package Versions"
echo "  d) Clean Build Folder (⇧⌘K)"
echo "  e) Build (⌘B)"
echo ""
echo "If still not working, check Build Settings:"
echo "  - Select your target"
echo "  - Build Settings → Search for 'Swift Compiler - Search Paths'"
echo "  - Ensure 'Import Paths' includes ${BUILT_PRODUCTS_DIR}"
