#!/bin/bash
echo "🔧 Xcode Reference Fix Instructions"
echo "==================================="
echo ""
echo "Since the files exist on disk but not in Xcode, try this:"
echo ""
echo "1. In Xcode, check if there are any RED (missing) file references:"
echo "   - Look for any red filenames in the project navigator"
echo "   - If found, right-click and delete the references"
echo ""
echo "2. Use Finder to drag files into Xcode:"
echo "   - Open Finder to this location:"
echo "   $(pwd)/class-notes-frontend/ClassNotes/Core/Networking/gRPC/"
echo ""
echo "3. Drag these files into the Xcode project navigator:"
echo "   - From Generated/: classnotes_service.pb.swift"
echo "   - From Generated/: classnotes_service.grpc.swift"  
echo "   - From Extensions/: GRPCImports.swift"
echo ""
echo "4. When Xcode asks, ensure:"
echo "   - ✅ Create groups (not folder references)"
echo "   - ✅ Add to targets: class-notes-frontend"
echo ""
echo "The files are here:"
find class-notes-frontend -name "*.swift" -path "*Generated*" -o -name "GRPCImports.swift" | grep -E "(Generated|GRPCImports)"
