# SwiftLint configuration for Class Notes

# Paths to include
included:
  - ClassNotes

# Paths to exclude
excluded:
  - .build
  - DerivedData
  - Pods
  - .swiftpm
  - ClassNotes/Resources/Generated

# Rule configuration
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_type_interface
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - ibinspectable_in_extension
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - test_case_accessibility
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo
  - line_length
  - type_body_length
  - file_length
  - cyclomatic_complexity
  - function_body_length
  - type_name

# Custom rules
custom_rules:
  no_hardcoded_strings:
    regex: '(^|[^"])("Class Notes"|"Authentication"|"Lessons")'
    message: "Avoid hardcoded strings. Use localized strings instead."
    severity: warning
    
  avoid_print:
    regex: '(^|\s)print\('
    message: "Avoid using print statements. Use proper logging instead."
    severity: warning

# Rule parameters
force_cast: error
force_try: error

identifier_name:
  excluded:
    - id
    - ok
    - no
    - on
    - to
    - up

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

vertical_whitespace:
  max_empty_lines: 2

# File header template
file_header:
  required_pattern: |
    //
    //  .*\.swift
    //  Class Notes
    //
    //  Created by .* on .*\.
    //  Copyright © .* Class Notes\. All rights reserved\.
    // 